
{% set data = load_setup_py_data() %}

package:
  name: dodcerts
  
  version: {{ data['version'] }}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests
  imports:
    - dodcerts

about:
  home: https://github.com/erdc/dodcerts
  summary: DoD Certificate Chain
